package com.example.adrianantonescu.qa.database;

public interface DatabaseConstants {
    String DATABASE_NAME = "QA.db";
    int DATABASE_VERSION = 1;

    String STUDENT_PROFILE_TABLE_NAME = "StudentProfile";
    String TEACHER_PROFILE_TABLE_NAME = "TeacherProfile";
    String STUDENT_SCORES_TABLE_NAME = "StudentScores";
    String DISTRIBUTION_TABLE_NAME = "Distribution";
    String COURSES_TABLE_NAME = "Courses";



    //tabela STUDENT_PROFILE

    String STUDENT_PROFILE_COLUMN_ID = "_id";
    String STUDENT_PROFILE_COLUMN_USERNAME = "username";
    String STUDENT_PROFILE_COLUMN_PASSWORD = "password";
    String STUDENT_PROFILE_COLUMN_FIRST_NAME = "first_name";
    String STUDENT_PROFILE_COLUMN_LAST_NAME = "last_name";
    String STUDENT_PROFILE_COLUMN_EMAIL = "email";
    String STUDENT_PROFILE_COLUMN_SPECIALIZATION = "specialization";
    String STUDENT_PROFILE_COLUMN_YEAR = "year";
    String STUDENT_PROFILE_COLUMN_SERIES = "series";
    String STUDENT_PROFILE_COLUMN_GROUP = "group";
    String STUDENT_PROFILE_COLUMN_BIO = "bio";

    String CREATE_TABLE_STUDENT_PROFILE = "CREATE TABLE " + STUDENT_PROFILE_TABLE_NAME + " (" + STUDENT_PROFILE_COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " +
            STUDENT_PROFILE_COLUMN_USERNAME + " TEXT NOT NULL, UNIQUE, " + STUDENT_PROFILE_COLUMN_PASSWORD + " TEXT NOT NULL, " + STUDENT_PROFILE_COLUMN_FIRST_NAME + " TEXT NOT NULL, " +
            STUDENT_PROFILE_COLUMN_LAST_NAME + " TEXT NOT NULL, " + STUDENT_PROFILE_COLUMN_EMAIL + " TEXT NOT NULL, UNIQUE, " +
            STUDENT_PROFILE_COLUMN_SPECIALIZATION + " TEXT NOT NULL, " + STUDENT_PROFILE_COLUMN_YEAR + " INTEGER NOT NULL, " +
            STUDENT_PROFILE_COLUMN_SERIES + " TEXT NOT NULL, " + STUDENT_PROFILE_COLUMN_GROUP + " INTEGER NOT NULL, " + STUDENT_PROFILE_COLUMN_BIO + " TEXT);";

    //tabela TEACHER_PROFILE

    String TEACHER_PROFILE_COLUMN_ID = "_id";
    String TEACHER_PROFILE_USERNAME = "username";
    String TEACHER_PROFILE_PASSWORD = "password";
    String TEACHER_PROFILE_COLUMN_FIRST_NAME = "first_name";
    String TEACHER_PROFILE_COLUMN_LAST_NAME = "last_name";
    String TEACHER_PROFILE_COLUMN_EMAIL = "email";
    String TEACHER_PROFILE_BIO = "bio";

    String CREATE_TABLE_TEACHER_PROFILE = "CREATE TABLE " + TEACHER_PROFILE_TABLE_NAME + " (" + TEACHER_PROFILE_COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " +
            TEACHER_PROFILE_USERNAME + " TEXT NOT NULL, UNIQUE, " + TEACHER_PROFILE_PASSWORD + " TEXT NOT NULL, " +
            TEACHER_PROFILE_COLUMN_FIRST_NAME + " TEXT NOT NULL, " + TEACHER_PROFILE_COLUMN_LAST_NAME + " TEXT NOT NULL, " + TEACHER_PROFILE_COLUMN_EMAIL + " TEXT NOT NULL, UNIQUE, " +
            TEACHER_PROFILE_BIO + " TEXT);";


    //tabela COURSES

    String COURSES_COLUMN_ID = "_id";
    String COURSES_COLUMN_NAME = "name";
    String COURSES_COLUMN_CREDITS = "credits";

    String CREATE_TABLE_COURSES = "CREATE TABLE " + COURSES_TABLE_NAME + " (" + COURSES_COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " + COURSES_COLUMN_NAME+ " TEXT NOT NULL, UNIQUE, " +
            COURSES_COLUMN_CREDITS + " INTEGER NOT NULL);";

    //tabela STUDENT_SCORES

    String STUDENT_SCORES_COLUMN_ID = "_id";
    String STUDENT_SCORES_COLUMN_STUDENT_ID = "studentID";
    String STUDENT_SCORES_COLUMN_COURSE_ID = "courseID";
    String STUDENT_SCORES_COLUMN_POINTS = "points";


    String CREATE_TABLE_STUDENT_SCORES = "CREATE TABLE "+ STUDENT_SCORES_TABLE_NAME + " (" + STUDENT_SCORES_COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " +
            STUDENT_SCORES_COLUMN_STUDENT_ID + " INTEGER NOT NULL, " + STUDENT_SCORES_COLUMN_COURSE_ID + " INTEGER NOT NULL, " + STUDENT_SCORES_COLUMN_POINTS + " INTEGER NOT NULL, FOREIGN KEY (" +
            STUDENT_SCORES_COLUMN_STUDENT_ID + ") REFERENCES " +  STUDENT_PROFILE_TABLE_NAME + "(" + STUDENT_PROFILE_COLUMN_ID + "), FOREIGN KEY (" +
            STUDENT_SCORES_COLUMN_COURSE_ID + ") REFERENCES " + COURSES_TABLE_NAME + "(" + COURSES_COLUMN_ID +"));";

    //tabela DISTRIBUTION

    String DISTRIBUTION_COLUMN_ID = "_id";
    String DISTRIBUTION_COLUMN_TEACHER_ID = "teacherID";
    String DISTRIBUTION_COLUMN_COURSE_ID = "courseID";

    String CREATE_TABLE_DISTRIBUTION = "CREATE TABLE " + DISTRIBUTION_TABLE_NAME + " (" + DISTRIBUTION_COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " +
            DISTRIBUTION_COLUMN_TEACHER_ID + " INTEGER NOT NULL, " + DISTRIBUTION_COLUMN_COURSE_ID + " INTEGER NOT NULL, FOREIGN KEY (" +
            DISTRIBUTION_COLUMN_TEACHER_ID + ") REFERENCES " + TEACHER_PROFILE_TABLE_NAME + "(" + TEACHER_PROFILE_COLUMN_ID + "), FOREIGN KEY (" + DISTRIBUTION_COLUMN_COURSE_ID +
            ") REFERENCES " + COURSES_TABLE_NAME + "(" + COURSES_COLUMN_ID + "));";

    String DROP_TABLE_STUDENT_PROFILE = "DROP TABLE IF EXISTS " + STUDENT_PROFILE_TABLE_NAME + ";";
    String DROP_TABLE_TEACHER_PROFILE = "DROP TABLE IF EXISTS " + TEACHER_PROFILE_TABLE_NAME + ";";
    String DROP_TABLE_STUDENT_SCORES = "DROP TABLE IF EXISTS " + STUDENT_SCORES_TABLE_NAME + ";";
    String DROP_TABLE_DISTRIBUTION = "DROP TABLE IF EXISTS " + DISTRIBUTION_TABLE_NAME + ";";
    String DROP_TABLE_COURSES = "DROP TABLE IF EXISTS " + COURSES_TABLE_NAME + ";";


}
